### PR TITLE
fix endpoint typo

### LINKED ISSUE #571: References to Canary endpoints in Graph Sample for Pages API
#### Category
- [X] Question
- [ ] Bug
- [ ] Enhancement

#### Expected or Desired Behavior

Check the endpoints.

#### Observed Behavior

Reading sample: https://github.com/pnp/sp-dev-solutions/blob/master/solutions/PagesAPISolution/PowerShell/PagesController.ps1 I have noticed this refers to graph endpoints that are the dogfood version, is this intended?

Also, can the sample (although tempted to write one) use the new Graph PowerShell V2 SDK? 

#### Steps to Reproduce

Read the script, references on line: 
https://github.com/pnp/sp-dev-solutions/blob/847e54491cfb08f28f979709cd359d30c77b60bb/solutions/PagesAPISolution/PowerShell/PagesController.ps1#L136

Thanks for your contribution! Sharing is caring.

### PR DESCRIPTION
**Pull request by sangle7**
| Q               | A
| --------------- | ---
| Bug fix?        | Yes
| New feature?    | No
| New sample?      | No
| Related issues?  | fixes #571 

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by sangle7** [comment]
@VesaJuvonen  could you please help to merge this? Thanks!

**Comment by wobba** [comment]
@sangle7 why did you close this one? looked ok to merge to me.

**Comment by sangle7** [comment]
@wobba  lol I see that this PR has not been updated for a long time and I include this change in my another PR. But it's ok to merge. Thanks!

**Comment by wobba** [comment]
Noticed the age of it as well 😅

**Pull request merged**
