### PR TITLE
Introduce more sample code for Pages API phase 2

### PR DESCRIPTION
**Pull request by sangle7**
| Q               | A
| --------------- | ---
| Bug fix?        | N
| New feature?    | N
| New sample?      | Y
| Related issues?  | N/A

#### What's in this Pull Request?

Introduce more sample code for Pages API phase 2

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'dev' branch.*

Thanks for your contribution! Sharing is caring.

### CODE REVIEW

**Comment by wobba** [comment]
@sangle7 looks good, let me know if you plan to push more commits or not 🙂

**Comment by sangle7** [comment]
@wobba Thanks for review! We're targeting next week to merge this PR. (waiting for code reach prod) 
I'll let you know when it's ready :)

**Comment by sangle7** [comment]
@wobba It's ready to merge. Thanks for your help!

**Comment by wobba** [comment]
Thank you :)

**Pull request merged**
